name: "Versioning Branch Semantic"
description: "Calculate next version from branch name and semantic rules"

inputs:
  branch:
    description: "Branch name"
    required: true
  prerelease:
    description: "Whether it is prerelease mode"
    required: false
    default: "false"
  config-file:
    description: "Path to TOML config"
    required: false
    default: "pyproject.toml"

outputs:
  version:
    description: "Calculated version"
    value: ${{ steps.calc.outputs.version }}
  deploy:
    description: "Whether deployment should happen"
    value: ${{ steps.calc.outputs.deploy }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - uses: astral-sh/setup-uv@v3

    - name: Calculate version
      id: calc
      shell: bash
      run: |
        set -euo pipefail
        result=$(uv run --with-requirements "${{ github.action_path }}/requirements.txt" \
          python "${{ github.action_path }}/src/cli.py" \
          --branch "${{ inputs.branch }}" \
          --prerelease "${{ inputs.prerelease }}" \
          --config "${{ inputs.config-file }}")

        version=$(echo "$result" | awk -F= '/^version=/{print $2}')
        deploy=$(echo "$result" | awk -F= '/^deploy=/{print $2}')

        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "deploy=$deploy" >> "$GITHUB_OUTPUT"
